# Generated by Django 2.1.7 on 2019-03-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_cadastro', '0003_remove_cadastro_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='cMaisMais',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='cSharp',
        ),
    ]
